defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

exclude:
- assets/css/style.css
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Gemfile
- Gemfile.lock
- LICENSE
- new_post
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- setup.sh
- site.code-workspace
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap

url: "https://redtide.github.io/wiki-x-air"

spdx_license_id: "CC0-1.0"

organization:
  name: "X-AIR"
  url: "https://github.com/redtide/wiki-x-air"

authors:
  content: "Behringer"
  web: "redtide"
